import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{
        backgroundRepeat: "no-repeat",
        background: `url(http://atelierdart.de/_include/img/slider-images/image01.jpg)`,
        backgroundSize: "cover",
        backgroundAttachment: "fixed",
      }}>
        {children}
      </body>
    </html>
  );
}
